### ISSUE TITLE
cannot assign to `inject_ok` because it is borrowed

### ISSUE THREAD

**Issue by aadog** [rodrigocfd/defer-lite#1]
```
let mut inject_ok = false;
    defer! {
        let x=inject_ok;
        println!("{}",x);
    //     if inject_ok.to_owned(){
    //         //如果不成功就释放内存
    //         VirtualFreeEx(h_process,target_base,0,MEM_RELEASE);
    //     }
    }

    println!("run {}",inject_ok);
    inject_ok=false;
```

**Comment by rodrigocfd** [comment]
This error has nothing to do with the library.

The `defer!` macro executes the code in a closure, and when you pass `inject_ok` into this closure, it's borrowed, therefore it cannot be used outside of it. [See here for further details](https://stackoverflow.com/q/45623879/6923555).

Anyway, looking at your logic, it seems that a `struct` encapsulating the logic and implementing the [`Drop` trait](https://doc.rust-lang.org/std/ops/trait.Drop.html) would suit you better (that is, implementing a [RAII guard](https://rust-unofficial.github.io/patterns/patterns/behavioural/RAII.html)). Something like:

```rust
fn main() {
	let mut injector = Injector::new();

	injector.inject_ok = true;

	// releasing is done automatically if needed...
}

pub struct Injector {
	pub inject_ok: bool,
	// data to be released...
}

impl Drop for Injector {
	fn drop(&mut self) {
		if self.inject_ok {
			// release your stuff...
		}
	}
}

impl Injector {
	pub fn new() -> Self {
		Self { inject_ok: false }
	}
}
```
