### ISSUE TITLE
async / await inside defer!

### ISSUE THREAD

**Issue by GOVYANSONG** [rodrigocfd/defer-lite#2]
can async/await be used within the defer! macro?

**Comment by rodrigocfd** [comment]
I never tried. The code is [extremely straightforward](https://github.com/rodrigocfd/defer-lite/blob/master/src/lib.rs#L21) though, it's just a [`FnOnce`](https://doc.rust-lang.org/std/ops/trait.FnOnce.html) closure being stored locally, then called after its current scope.

So, in theory, anything that can be called in a `FnOnce` closure can be called inside `defer!`.

Please let me know the results of any test you do, I'm interested.

**Comment by GOVYANSONG** [comment]
i have this code snippet and rust compiler complained about the code is not in async block:

defer! 
    { 
        handle.close();
        signals_task.await?;
    }

**Comment by GOVYANSONG** [comment]
from docs:

https://doc.rust-lang.org/std/ops/trait.FnOnce.html
https://rust-lang.github.io/async-fundamentals-initiative/roadmap/async_closures.html

it led me to believe that there is a need for async version of defer!.

**Comment by rodrigocfd** [comment]
I never worked with async Rust before, so I'm studying it now, but it seems to be the case. Maybe there's a way to have it in the same macro, I'm going deep on this.

**Comment by GOVYANSONG** [comment]
I tried with tokio block_on and in vain. instead, i got it to work with async_std:

defer_lite::defer! {
        async_std::task::block_on(async {
            eprintln!("blocking");
            handle.close();
            signals_task.await.unwrap();
        });
    }

**Comment by rodrigocfd** [comment]
That's great, thanks for the feedback.

**Comment by Noah-Kennedy** [comment]
Going to say something here I said in another issue:

> This isn't a problem which has any good solutions right now. There is discussion right now around eventually getting an AsyncDrop trait to allow for async drop implementations, but I am doubtful that this will ever be implemented.
>
> I can't think of a non-terrible way to do this. Spawning an inner runtime to do the blocking (in the case of tokio you'd need to spawn a temp thread for the "inner" runtime) technically works, but is going to be pretty expensive for what you are doing and also has the issue that you are going to be blocking a worker the entire time that you spawn the inner runtime and run the destructor, which, in the case of async code, could be a while. I could potentially see this causing a lot of valid-looking user code to deadlock if that code assumed that other tasks on the runtime were progressing normally, as a current_thread runtime would never progress any tasks while the inner runtime was operating.

**Comment by Noah-Kennedy** [comment]
In short, this is a language-level problem that isn't really solvable right now in the ecosystem. You'd basically need a form of async destructors to make this work.

**Comment by GOVYANSONG** [comment]
after getting help from tokio forum, following solution based on tokio is more robuts:

defer_lite::defer! {
        tokio::task::block_in_place(move || {
            tokio::runtime::Handle::current().block_on(
                async move {
                    eprintln!("deferred logic execution");
                    handle.close();
                    signals_task.await.unwrap();
                }
            );
        });
    }

**Comment by Noah-Kennedy** [comment]
This will work for the `multi_threaded` tokio runtime, but not for the `current_thread` runtime.
